# Generated by Django 5.0.1 on 2024-01-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True, 'verbose_name': 'producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelTable(
            name='productos',
            table='',
        ),
    ]
